<<<<<<< HEAD
spring.config.import=optional:file:.env[.properties]
=======
spring.config.import=optional:file:.env[.properties],optional:file:../bidmart-infrastructure/.env[.properties]
>>>>>>> 8eafe528816cf21eb420620d439fc17c3edb1a0e
